### ISSUE TITLE
TouchUI incompatibility

### ISSUE THREAD

**Issue by xoan** [jneilliii/OctoPrint-FloatingNavbar#1]
When FloatingNavbar is enabled, [TouchUI](https://github.com/BillyBlaze/OctoPrint-TouchUI) is not usable because tabs are hidden:

![screenshot_2018-01-23-08-21-35-686_com android chrome](https://user-images.githubusercontent.com/288246/35263123-dfe2bbee-0017-11e8-9560-e09b7e73cff9.png)

Normal behaviour, FloatNavbar disabled:

![screenshot_2018-01-23-08-23-21-132_com android chrome](https://user-images.githubusercontent.com/288246/35263112-cba5a43e-0017-11e8-94ca-9c6c88456a7f.png)

**Comment by jneilliii** [comment]
Just release a new version 0.2.0 that should fix this issue.
