### ISSUE TITLE
Adjustable buffer space?

### ISSUE THREAD

**Issue by TheKrush** [jneilliii/OctoPrint-FloatingNavbar#5]
Right now the plugin always forces +20 to the size when in my testing with Themify +15 is good enough for the Discorded theme. Would it be possible for this plugin to add a setting that allows for changing that +20 to another number?

**Comment by jneilliii** [comment]
@TheKrush, if you don't mind testing before I release that would be great.  Install the updated version using the below url in plugin manager and let me know how it works for you.  If all is good I'll push the update to an official release. Once updated go into OctoPrint Settings > Floating Navbar and adjust the `Height Buffer` to what you want.

https://github.com/jneilliii/OctoPrint-FloatingNavbar/archive/0.3.1.zip
